# Generated by Django 3.2.4 on 2021-07-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=None, null=True)),
                ('phone_number', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('city', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
    ]
